name: reviews_slider
description: Animation widget with changing smile to collect users review grade.
author: Kherel Kechil <kherel@gmail.com>
homepage: https://github.com/kherel/reviews_slider

version: 1.0.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
